Add "shift and scale" input for `preload` method
nndt-team/nndt pull request #194
Opened 2022-11-22 07:34 UTC by semyon-v-dot

2022-11-25 09:23 UTC, Maikenov commented
please do the same for "to_cube"

2022-11-25 10:27 UTC, Maikenov approved these changes

2022-11-25 11:25 UTC, Dopervigest requested changes
If you are adding support for both inputs, underscore-separated and space-separated, add the same feature to "to_cube" preload mode

2022-12-06 15:18 UTC, Dopervigest approved these changes
legit

2022-12-08 07:05 UTC, merged